ci: update test flow

diff --git a/.github/workflows/flutter_test.yml b/.github/workflows/flutter_test.yml
--- a/.github/workflows/flutter_test.yml
+++ b/.github/workflows/flutter_test.yml
@@ -65,17 +65,46 @@ jobs:
           flutter pub get
 
       - name: ✨ Check Formatting
-        run: dart format --line-length ${{inputs.format_line_length}} --set-exit-if-changed ${{inputs.format_directories}}
+        run: |
+          dart format --line-length ${{inputs.format_line_length}} --set-exit-if-changed ${{inputs.format_directories}}
+          check=$?
+          echo "CHECK_FORMAT=($check)" >> $GITHUB_ENV
+          return $check
+          
         continue-on-error: true
 
       - name: 🕵️ Analyze
-        run: flutter analyze ${{inputs.analyze_directories}}
+        run: |
+          flutter analyze ${{inputs.analyze_directories}}
+          check=$?
+          echo "CHECK_ANALYZE=($check)" >> $GITHUB_ENV
+          return $check
         continue-on-error: true
 
       - name: 🧪 Run Tests
-        run: flutter test --test-randomize-ordering-seed random
+        run: | 
+          flutter test --test-randomize-ordering-seed random
+          check=$?
+          echo "CHECK_TEST=($check)" >> $GITHUB_ENV
+          return $check
       
       - name: 🚀 Results
         run: |
-          echo "### 🎉 All tests passed! :rocket:" >> $GITHUB_STEP_SUMMARY
+          IF [ $CHECK_FORMAT -ne 0 ]; THEN
+            echo "### ❌ Formatting check failed!" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          IF [ $CHECK_ANALYZE -ne 0 ]; THEN
+            echo "### ❌ Analyze check failed!" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          IF [ $CHECK_TEST -ne 0 ]; THEN
+            echo "### ❌ Test check failed!" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          IF [ $CHECK_FORMAT -eq 0 ] && [ $CHECK_ANALYZE -eq 0 ] && [ $CHECK_TEST -eq 0 ]; THEN
+            echo "### ✅ All checks passed!" >> $GITHUB_STEP_SUMMARY
+          fi
+        continue-on-error: true
+          
 
